<a href="https://colab.research.google.com/github/melvinsackaria/DeepLearning/blob/main/WordEmbeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size - size of dictionary
voc_size=10000

**One Hot Representation**


In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)#We will be getting index of words from the dictionary

[[4232, 7611, 9798, 7605], [4232, 7611, 9798, 8306], [4232, 289, 9798, 8074], [1335, 8967, 8926, 6459, 8145], [1335, 8967, 8926, 6459, 9616], [6088, 4232, 7072, 9798, 9996], [3640, 5834, 9560, 6459]]


**Word Embedding Represntation**

Changing to embedding matrix, importanat parameter is the dimensions


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences # padding to have all sentences same number of words before sending to embedding layer
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8 # maximum sentance length i want, padding on top of that
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) # one hot resp as input, pre - before the word
print(embedded_docs)

[[   0    0    0    0 4232 7611 9798 7605]
 [   0    0    0    0 4232 7611 9798 8306]
 [   0    0    0    0 4232  289 9798 8074]
 [   0    0    0 1335 8967 8926 6459 8145]
 [   0    0    0 1335 8967 8926 6459 9616]
 [   0    0    0 6088 4232 7072 9798 9996]
 [   0    0    0    0 3640 5834 9560 6459]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
#print(model.predict(embedded_docs))

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 4232, 7611, 9798, 7605], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])

[[-0.01802969  0.03989239 -0.02373035  0.04699631 -0.00284908 -0.0160761
  -0.04844203 -0.04134765  0.04460403 -0.00746163]
 [-0.01802969  0.03989239 -0.02373035  0.04699631 -0.00284908 -0.0160761
  -0.04844203 -0.04134765  0.04460403 -0.00746163]
 [-0.01802969  0.03989239 -0.02373035  0.04699631 -0.00284908 -0.0160761
  -0.04844203 -0.04134765  0.04460403 -0.00746163]
 [-0.01802969  0.03989239 -0.02373035  0.04699631 -0.00284908 -0.0160761
  -0.04844203 -0.04134765  0.04460403 -0.00746163]
 [ 0.04941711  0.00588239  0.00263337 -0.03533729  0.01008414  0.04056365
   0.02721019  0.02660996  0.01571821 -0.03454082]
 [-0.0457071  -0.02795789 -0.04754693  0.02753275  0.00427162 -0.01414029
  -0.03358044  0.03344137 -0.03008206 -0.02891111]
 [ 0.00328799 -0.03098323  0.03369984  0.03305835 -0.00208652  0.03132438
   0.03331438  0.03541584 -0.0332818   0.04799228]
 [ 0.04659632  0.02723899 -0.0220552  -0.00670103  0.02085446  0.01150701
  -0.00225363  0.03400402 -0.0407638  -0.02487596]]
